version: "3.4"

services:

  web_server:
    build:
      context: services/nginx
    container_name: store_app_nginx
    volumes:
      - ./services/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./services/nginx/sites-available:/etc/ngnix/site-available
      - ./web_store:/var/www/web_store
    ports:
      - "2101:2101"
    environment:
      - NGINX_PORT=80
    links:
      - php
    networks:
      - store_app
    restart: "unless-stopped"

  php:
    container_name: store_app_php
    build:
      context: services/php-fpm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    restart: "unless-stopped"
    networks:
      - store_app
    volumes:
      - ./web_store:/var/www/web_store
  
  store_app_db_mysql:
    image: mysql:5.7
    container_name: store_app_db_mysql
    command:
      - --innodb_buffer_pool_size=10M
      - --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: web_store
    networks:
      - store_app
    restart: "unless-stopped"
    volumes:
      - ./store_app_db_mysql/:/var/lib/mysql
      - ./databases:/docker-entrypoint-initdb.d

  store_app_phpmyadmin:
    image: phpmyadmin:latest
    container_name: store_app_phpmyadmin
    restart: "unless-stopped"
    depends_on:
      - store_app_db_mysql
    ports:
      - "2100:80"
    environment:
      PMA_HOST: store_app_db_mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - store_app

networks:
  store_app:
    driver: bridge
